language: php

php:
  - 7.1
  - 7.1snapshot
  - 7.2
  - 7.2snapshot
  - 7.3
  - 7.3snapshot

branches:
  only:
    - master
    - development
    - /^feature\/.+$/
    - /^refactoring\/.+$/
    - /^issue\/.+$/

before_script:
  - echo $(phpenv version-name)
  - sudo mkdir -pm 0777 /var/run
  - sudo usermod -a -G travis www-data
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - echo -e "[global]\ninclude=/home/travis/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/*.conf" > ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp .docker/php/network-socket.pool.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/network-socket.pool.conf
  - sudo cp .docker/php/unix-domain-socket.pool.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/unix-domain-socket.pool.conf
  - sudo cp .docker/php/restricted-unix-domain-socket.pool.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/restricted-unix-domain-socket.pool.conf
  - sudo ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git checkout "$TRAVIS_BRANCH"; else git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH"; fi
  - git reset --hard "$TRAVIS_COMMIT"
  - composer self-update
  - mkdir -p vendor/bin
  - mkdir -p build/logs
  - composer install -o --prefer-dist --no-interaction
  - sudo chmod 0200 test/Integration/Workers/inaccessibleWorker.php

script:
  - php vendor/bin/phpstan.phar analyze --level max src/
  - php vendor/bin/phpunit.phar -c build/ --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry bash <(curl -s https://codecov.io/bash)
