name: FastCGI Client CI PHP 7.1 - 8.0

on:
  push:
    branches:
      - master
      - development

    tags:
      - 'v*.*.*'

  pull_request:

  schedule:
    - cron: "7 7 * * *"

jobs:
  static-analyzers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for PHP parse errors
        run: docker run --rm -v $(pwd):/app php:7.4-cli -c 'find /app/src -type f -name "*.php" -print0 | xargs -0 -n1 -P8 php -l -n | (! grep -v "No syntax errors detected" )'

      - name: Composer validate
        run: docker run --rm -v $(pwd):/app composer validate

      - name: Composer update
        run: docker run --rm -v $(pwd):/app composer update -o -v

      - name: Run PHPStan
        run: docker run --rm -v $(pwd):/app phpstan/phpstan analyze

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build environment
        run: make update

      - name: Run unit tests on PHP 7.1
        run: make test-php-71 -s
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
          PHPUNIT_OPTIONS: "--coverage-clover=/repo/coverage.xml --testdox"

      - name: Upload code coverage to codecov.io
        run: bash <(curl -s https://codecov.io/bash)

      - name: Run unit tests on PHP 7.2
        run: make test-php-72 -s
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
          PHPUNIT_OPTIONS: "--coverage-clover=/repo/coverage.xml --testdox"

      - name: Upload code coverage to codecov.io
        run: bash <(curl -s https://codecov.io/bash)

      - name: Run unit tests on PHP 7.3
        run: make test-php-73 -s
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
          PHPUNIT_OPTIONS: "--coverage-clover=/repo/coverage.xml --testdox"

      - name: Upload code coverage to codecov.io
        run: bash <(curl -s https://codecov.io/bash)

      - name: Run unit tests on PHP 7.4
        run: make test-php-74 -s
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
          PHPUNIT_OPTIONS: "--coverage-clover=/repo/coverage.xml --testdox"

      - name: Upload code coverage to codecov.io
        run: bash <(curl -s https://codecov.io/bash)

      - name: Run unit tests on PHP 8.0
        run: make test-php-80 -s
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
          PHPUNIT_OPTIONS: "--testdox"

  release:
    needs:
      - static-analyzers
      - unit-tests

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract version
        id: data
        run: |
          # Strip git ref prefix from version
          RELEASE_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && RELEASE_VERSION=$(echo $RELEASE_VERSION | sed -e 's/^v//')

          echo $RELEASE_VERSION
          echo "##[set-output name=version;]$RELEASE_VERSION"

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Version ${{ steps.data.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}